Vagrant.configure("2") do |config|

  #General configuration
  config.ssh.username = "admin"
  config.ssh.private_key_path = "./files/acit_admin_id_rsa"
  
  #Specifiy the base box here
  config.vm.box = "ansible_4640"

  #VM specific configuration
  config.vm.define "todoapp" do |todoapp|
    todoapp.vm.hostname = "todoapp.bcit.local"
    todoapp.vm.network "forwarded_port", guest: 80, host: 50080
	todoapp.vm.synced_folder ".", "/vagrant", disabled: true
	#todoapp.vm.provision "file", source: "./files/nginx.conf", destination: "/home/admin/nginx.conf"
	
  #ToDo provisioning Configuration 
	#todoapp.vm.provision "shell" do |shell|
	  #shell.path = "vagrant.sh"
	#end
	
	config.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/todoapp.yaml"
    end

    #other machine configuration items go here
    todoapp.vm.provider "virtualbox" do |vb|
      vb.name = "TODO_4640"
	  vb.linked_clone = true
    end
  end
  
end