---
  - block:
    - name: disassociate elastic IP from ec2 instance
      ec2_eip:
        state: 'absent'
        region: '{{ aws_region }}'
        device_id: '{{ instance_id }}'
        ip: '{{ public_ip_address }}'
        release_on_disassociation: true

    - name: remove ec2 instance
      ec2:
        wait: yes
        state: 'absent'
        region: '{{ aws_region }}'
        instance_ids: '{{ instance_id }}'

    - name: remove routing table
      ec2_vpc_route_table:
        vpc_id: '{{ vpc_id }}'
        region: '{{ aws_region }}'
        lookup: tag
        tags:
          Name: '{{ vpc_prefix }}_rt'
        state: 'absent'
        
    - name: remove gateway
      ec2_vpc_igw:
        state: 'absent'
        region: '{{ aws_region }}'
        vpc_id: '{{ vpc_id }}'

    - name: remove subnet
      ec2_vpc_subnet:
        state: 'absent'
        region: '{{ aws_region }}'
        az: '{{ aws_az }}'
        cidr: '{{ vpc_subnet_cidr }}'
        vpc_id: '{{ vpc_id }}'

    - name: remove security group
      ec2_group:
        state: 'absent'
        region: '{{ aws_region }}'
        group_id: '{{ security_groups[0].group_id }}'
        vpc_id: '{{ vpc_id }}'
        tags:
          Name: '{{ vpc_prefix }}_SecGroup'

    - name : remove VPC 
      ec2_vpc_net:
        region: '{{ aws_region }}'
        cidr_block: '{{ vpc_cidr }}'
        name: '{{ vpc_prefix }}_VPC'
        state: 'absent'

    when: instance_id != ''